### ISSUE TITLE
 Remote SDP never received.

### ISSUE THREAD

**Issue by akshayiosdeveloper** [stasel/WebRTC-iOS#141] opened 2023-10-12 10:08 UTC
<img width="1425" alt="Screenshot 2023-10-12 at 3 34 38 PM" src="https://github.com/stasel/WebRTC-iOS/assets/7240581/8d2d12dd-16cb-4b71-bdfe-b91635eac275">

<img width="1387" alt="Screenshot 2023-10-12 at 3 33 43 PM" src="https://github.com/stasel/WebRTC-iOS/assets/7240581/70fa7754-092f-441f-ae23-c3e99e6d262d">

**Comment by stasel** [comment] 2023-10-13 20:45
Duplicate of #140

**Closed by stasel** 2023-10-13 20:45 UTC
