### ISSUE TITLE
No video after first call

### ISSUE THREAD

**Issue by Ivan411** [stasel/WebRTC-iOS#3] opened 2018-09-13 09:38 UTC
I do not see the video when I sendOffer again(after first sendOffer remoteCandidateCount = 52, after second = 104, but in VideoViewController I do not see anything). Local candidate in first call = 3, in second 0.  I get 3 Local candidate about every 1 minute, if I do nothing

**Comment by Ivan411** [comment] 2018-09-21 06:19
We tested on real device or simulator. We call to browser(Chrome). In first call all OK, but in second we haven`t video, but Remote candidate are coming

**Comment by stasel** [comment] 2018-09-23 17:54
Your instructions are not clear enough
Can you please provide the exact steps to reproduce the issue on the demo app?

**Comment by stasel** [comment] 2018-10-31 14:34
Hello, I am closing this issue due to lack fo response.
Please feel free to reopen the issue if you have further question/problems related to it.

**Closed by stasel** 2018-10-31 14:34 UTC
